// On-device transaction categorizer: TF-IDF + LogisticRegression in ONNX.
//
// The model itself is a sklearn LogisticRegression exported via skl2onnx
// (see tools/categorizer/train.py). It expects a dense Float32 vector of
// length |vocab| as input; the TF-IDF transform that produces that vector
// runs in pure Dart so the model file stays small and the algorithm is
// inspectable from the app side.
//
// Tokeniser implements sklearn's TfidfVectorizer(analyzer='char_wb',
// ngram_range=(3,5), lowercase=True) byte-for-byte. The parity test in
// test/features/transactions/ml_category_classifier_test.dart asserts
// the Dart implementation produces the same sparse vectors as Python on
// a curated set of inputs (vocab/test_vectors.json — generated by
// train.py at training time).
//
// The classifier loads gracefully when the model assets are missing
// (e.g. fresh clone, before the first training run): `load()` returns
// null and the `Categorizer` façade falls through to the legacy keyword
// matcher. No code change ever needs to add an "if missing" branch
// outside of this file.

import 'dart:convert';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:onnxruntime/onnxruntime.dart';

import '../models/category.dart';

/// One ML prediction. `categoryId` is resolved to the household's
/// matching category (by name) — null when the predicted category
/// doesn't exist in the supplied list (e.g. household has no
/// "Subscriptions" custom category).
class MlPrediction {
  const MlPrediction({
    required this.categoryName,
    required this.categoryId,
    required this.confidence,
  });

  final String categoryName;
  final String? categoryId;
  final double confidence;
}

/// Wraps an ONNX category-classifier model. Construct via [load].
class MlCategoryClassifier {
  MlCategoryClassifier._({
    required OrtSession session,
    required TfidfVectoriser vectoriser,
    required List<String> labels,
  })  : _session = session,
        _vectoriser = vectoriser,
        _labels = labels;

  final OrtSession _session;
  final TfidfVectoriser _vectoriser;
  final List<String> _labels;

  /// Number of input features the model expects (== vocabulary size).
  int get inputSize => _vectoriser.vocabSize;

  /// Loads the model + vocab + label index from `assets/ml/`.
  ///
  /// Returns null when any asset is missing or unreadable — callers
  /// should treat this as "ML disabled, fall back to the keyword
  /// matcher". OrtEnv must be initialised once before this is called
  /// (see main.dart).
  static Future<MlCategoryClassifier?> load() async {
    try {
      final vocabJson = await rootBundle.loadString('assets/ml/vocab.json');
      final labelsJson = await rootBundle.loadString('assets/ml/labels.json');
      final modelBytes = await rootBundle.load('assets/ml/category_model.onnx');

      final vectoriser = TfidfVectoriser.fromJson(
        jsonDecode(vocabJson) as Map<String, dynamic>,
      );
      final labels = (jsonDecode(labelsJson) as List).cast<String>();
      final session = OrtSession.fromBuffer(
        modelBytes.buffer.asUint8List(),
        OrtSessionOptions(),
      );
      return MlCategoryClassifier._(
        session: session,
        vectoriser: vectoriser,
        labels: labels,
      );
    } catch (_) {
      // Most common path on a fresh clone: assets/ml/ is empty because
      // training hasn't been run yet. Silently disable ML; the façade
      // takes care of falling through.
      return null;
    }
  }

  /// Predicts the category for a single transaction.
  ///
  /// Returns null when the model's top-class probability is below
  /// [minConfidence] (caller should fall back to the keyword matcher),
  /// or when the predicted category is not present in [categories].
  ///
  /// [description], [merchant], and the sign of [amountCents] are
  /// rendered into the same string format used during training:
  /// `"<description>|<merchant or empty>|<+/->"`.
  MlPrediction? predict({
    required String description,
    String? merchant,
    required int amountCents,
    required List<Category> categories,
    double minConfidence = 0.55,
  }) {
    final input = _renderInput(description, merchant, amountCents);
    final vector = _vectoriser.transform(input);
    final (idx, confidence) = _runOnce(vector);
    if (confidence < minConfidence) return null;

    final name = _labels[idx];
    final cat = categories.where((c) => c.name == name).firstOrNull;
    return MlPrediction(
      categoryName: name,
      categoryId: cat?.id,
      confidence: confidence,
    );
  }

  /// Frees the native OrtSession. Call this when shutting the app down
  /// — Riverpod's `ref.onDispose` is the natural place.
  void dispose() => _session.release();

  // ── Private inference helpers ─────────────────────────────────────────────

  (int, double) _runOnce(Float32List vector) {
    final tensor = OrtValueTensor.createTensorWithDataList(
      vector,
      [1, vector.length],
    );
    final inputName = _session.inputNames.first;
    final outputs = _session.run(OrtRunOptions(), {inputName: tensor});
    tensor.release();

    // skl2onnx LogisticRegression export convention:
    //   outputs[0] — predicted label tensor (we re-derive from probs
    //                for confidence; either source works)
    //   outputs[1] — probability map per class (Map<String, double> as
    //                a list-of-maps; we just take the values in label
    //                order from the second output's tensor data).
    // We bypass the prediction tensor and pick argmax of the proba
    // tensor so we get a confidence number along with the index.
    final probaTensor = outputs[1];
    final probs = _readProbaRow(probaTensor);
    for (final out in outputs) {
      out?.release();
    }
    var bestIdx = 0;
    var best = probs[0];
    for (var i = 1; i < probs.length; i++) {
      if (probs[i] > best) {
        best = probs[i];
        bestIdx = i;
      }
    }
    return (bestIdx, best);
  }

  /// skl2onnx wraps proba output as a tensor of either Float32 or as a
  /// list-of-maps depending on opset. Handle both shapes; assume one row.
  List<double> _readProbaRow(OrtValue? tensor) {
    if (tensor == null) {
      throw StateError('ONNX model produced no probability output');
    }
    final raw = tensor.value;
    if (raw is List && raw.isNotEmpty && raw.first is Map) {
      // Map output: [{label: prob, ...}]
      final row = (raw.first as Map).cast<dynamic, num>();
      return [for (final lbl in _labels) (row[lbl] ?? 0).toDouble()];
    }
    if (raw is List && raw.isNotEmpty && raw.first is List) {
      return (raw.first as List).cast<num>().map((n) => n.toDouble()).toList();
    }
    throw StateError(
      'Unexpected proba output type: ${raw.runtimeType}',
    );
  }

  static String _renderInput(String description, String? merchant, int amount) {
    final sign = amount > 0 ? '+' : '-';
    return '$description|${merchant ?? ''}|$sign';
  }
}

// ── Char-WB TF-IDF, byte-compatible with sklearn's TfidfVectorizer ─────────

class TfidfVectoriser {
  TfidfVectoriser({
    required this.vocab,
    required this.idf,
    required this.minN,
    required this.maxN,
    required this.lowercase,
    required this.sublinearTf,
  });

  final Map<String, int> vocab;
  final Float32List idf;
  final int minN;
  final int maxN;
  final bool lowercase;
  final bool sublinearTf;

  int get vocabSize => idf.length;

  factory TfidfVectoriser.fromJson(Map<String, dynamic> j) {
    final analyzer = j['analyzer'] as String;
    if (analyzer != 'char_wb') {
      throw StateError(
        'Only char_wb analyzer is supported, got: $analyzer',
      );
    }
    final vocab = (j['vocabulary'] as Map<String, dynamic>)
        .map((k, v) => MapEntry(k, (v as num).toInt()));
    final idfList = (j['idf'] as List).cast<num>();
    final idf = Float32List(idfList.length);
    for (var i = 0; i < idfList.length; i++) {
      idf[i] = idfList[i].toDouble();
    }
    return TfidfVectoriser(
      vocab: vocab,
      idf: idf,
      minN: (j['ngram_min'] as num).toInt(),
      maxN: (j['ngram_max'] as num).toInt(),
      lowercase: j['lowercase'] as bool,
      sublinearTf: j['sublinear_tf'] as bool,
    );
  }

  /// Reproduces sklearn's `TfidfVectorizer.transform([s])[0]` and
  /// returns a single dense Float32 row of length [vocabSize].
  Float32List transform(String input) {
    final ngrams = charWbNgrams(input);

    // Term frequencies, restricted to the trained vocabulary.
    final counts = <int, double>{};
    for (final ng in ngrams) {
      final idx = vocab[ng];
      if (idx == null) continue;
      counts[idx] = (counts[idx] ?? 0) + 1;
    }

    final out = Float32List(vocabSize);
    if (counts.isEmpty) return out;

    counts.forEach((idx, tf) {
      final w = (sublinearTf ? (1 + math.log(tf)) : tf) * idf[idx];
      out[idx] = w;
    });

    // L2 normalisation (TfidfVectorizer default norm='l2').
    var sumSq = 0.0;
    for (var i = 0; i < out.length; i++) {
      sumSq += out[i] * out[i];
    }
    if (sumSq > 0) {
      final inv = 1.0 / math.sqrt(sumSq);
      for (var i = 0; i < out.length; i++) {
        out[i] = out[i] * inv;
      }
    }
    return out;
  }

  /// Returns the char_wb n-gram list for [text].
  ///
  /// Mirrors sklearn._char_wb_ngrams:
  ///   1. lowercase if configured
  ///   2. collapse whitespace runs to a single space
  ///   3. for each whitespace-bounded word, pad with " " on both sides
  ///   4. for each n in [minN..maxN], emit all overlapping n-grams from
  ///      the padded word; if the padded word fits in a single n-gram
  ///      (offset stays at 0), don't try larger n for this word.
  List<String> charWbNgrams(String text) {
    var doc = lowercase ? text.toLowerCase() : text;
    doc = doc.replaceAll(_whitespace, ' ');
    final ngrams = <String>[];
    for (final w in doc.split(' ')) {
      if (w.isEmpty) continue;
      final padded = ' $w ';
      final wLen = padded.length;
      for (var n = minN; n <= maxN; n++) {
        var offset = 0;
        ngrams.add(_safeSlice(padded, 0, n));
        while (offset + n < wLen) {
          offset += 1;
          ngrams.add(_safeSlice(padded, offset, offset + n));
        }
        if (offset == 0) break; // padded word fits in <= one n-gram
      }
    }
    return ngrams;
  }
}

// ── Helpers ────────────────────────────────────────────────────────────────

final RegExp _whitespace = RegExp(r'\s+');

String _safeSlice(String s, int start, int end) {
  final stop = end > s.length ? s.length : end;
  return s.substring(start, stop);
}

